/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contextmenu: typeof import('./src/components/MindMap/components/Contextmenu.vue')['default']
    ContextMenu: typeof import('./src/components/LevelMap/ContextMenu/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./src/components/LevelMap/ContextMenu/ContextMenuItem.vue')['default']
    copy: typeof import('./src/components/RepositoryList/index copy.vue')['default']
    CreateModal: typeof import('./src/components/RepositoryList/CreateModal.vue')['default']
    DragKit: typeof import('./src/components/LevelMap/levelBox/DragKit.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTree: typeof import('element-plus/es')['ElTree']
    LevelItem: typeof import('./src/components/LevelMap/levelBox/levelItem.vue')['default']
    LevelMap: typeof import('./src/components/LevelMap/LevelMap.vue')['default']
    Mindmap: typeof import('./src/components/MindMap/Mindmap.vue')['default']
    RepositoryList: typeof import('./src/components/RepositoryList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleController: typeof import('./src/components/MindMap/components/ScaleController.vue')['default']
    TableItem: typeof import('./src/components/TableMap/tableBox/tableItem.vue')['default']
    TableMap: typeof import('./src/components/TableMap/TableMap.vue')['default']
  }
}
